### ISSUE TITLE
Support to Spark 3.0 and ReadStream 

### ISSUE THREAD

**Issue by luancaarvalho** [tharwaninitin/etlflow#73]
Hello !

Two questions, please :
1) Is ETLFLOW already support spark 3.0?
2) In ETLFLOW is possible to invocate a readstream of spark structured streaming or just the normal read ? 

Thank you !

**Comment by tharwaninitin** [comment]
Sorry for delayed response, here are your answers 
1) No but spark steps uses most common api's of spark which are not that changed in 3.0 so it should be easy to test by upgrading spark version in build.sbt.
2) No there are no spark streaming steps added by default.
